Place.create!(name: '掃除機',)
Place.create!(name: 'センターテーブル＋丸テーブル',)
Place.create!(name: 'ロッカー',)
Place.create!(name: '水やり',)
Place.create!(name: 'ディスプレイ',)
Place.create!(name: '面談室１，２',)

Sweeper.create!(name: '掃除機：面談室１', day: 'Monday')
Sweeper.create!(name: '掃除機：面談室２', day: 'Tuesday')
Sweeper.create!(name: '掃除機：利用者エリア１', day: 'Wednesday')
Sweeper.create!(name: '掃除機：利用者エリア２', day: 'Thursday')
Sweeper.create!(name: '掃除機：利用者エリア３', day: 'Friday')
Sweeper.create!(name: '掃除機：カフェエリア', day: 'Saturday')

User.create!(name: '藤永', furigana: 'ふじなが')
User.create!(name: '中田',furigana: 'なかた')
User.create!(name: '大高',furigana: 'おおたか')
User.create!(name: '高林',furigana: 'たかばやし')
User.create!(name: '辻尾',furigana: 'つじお')
User.create!(name: '増田',furigana: 'ますだ')
User.create!(name: '松尾',furigana: 'まつお')
User.create!(name: '武井',furigana: 'たけい')
User.create!(name: '八田',furigana: 'はった')
User.create!(name: '水本',furigana: 'みずもと')
User.create!(name: '空田',furigana: 'そらた')
User.create!(name: '宇谷',furigana: 'うたに')
User.create!(name: '小浜',furigana: 'こはま')
User.create!(name: '加藤',furigana: 'かとう')
User.create!(name: '江草',furigana: 'えぐさ')
User.create!(name: '金',furigana: 'きむ')
User.create!(name: '中林',furigana: 'なかばやし')
User.create!(name: '松下',furigana: 'まつした')
User.create!(name: '中川',furigana: 'なかがわ')
User.create!(name: '小甲',furigana: 'こかぶ')
User.create!(name: '藤田',furigana: 'ふじた')
User.create!(name: '畔倉',furigana: 'あぜくら')
User.create!(name: '工藤',furigana: 'くどう')
User.create!(name: '大野',furigana: 'おおの')
User.create!(name: '大西',furigana: 'おおにし')
User.create!(name: '下坂',furigana: 'しもさか')
User.create!(name: '原',furigana: 'はら')
User.create!(name: '進藤',furigana: 'しんどう')
User.create!(name: '池上',furigana: 'いけがみ')